name: Build REG-linux QT6

on:
  push: 
    branches: [ "*" ]

concurrency:
    group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
  contents: write

env:
  LANG: en_US.UTF-8
  LANGUAGE: en_US:en
  LC_ALL: en_US.UTF-8
  FORCE_UNSAFE_CONFIGURE: 1
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build REG-linux QT6
    runs-on: ubuntu-latest
    outputs:
      qtversion: ${{ steps.compile_step.outputs.qtversion }}
      sufixdate: ${{ steps.compile_step.outputs.sufixdate }}
      dorelease: ${{ false || steps.compile_step.outputs.dorelease }}
    strategy:
      matrix:
        platform: [bcm2711]
    steps:
      - name: Install compiling tools
        shell: bash
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
          build-essential \
          cmake \
          git \
          libncurses6 \
          libncurses-dev \
          libssl-dev \
          mercurial \
          texinfo \
          zip \
          default-jre \
          imagemagick \
          subversion \
          autoconf \
          automake \
          bison \
          scons \
          libglib2.0-dev \
          bc \
          gh \
          mtools \
          u-boot-tools \
          flex \
          wget \
          cpio \
          dosfstools \
          libtool \
          rsync \
          device-tree-compiler \
          gettext \
          locales \
          graphviz \
          python3 \
          python3-numpy \
          python3-matplotlib \
          gcc-multilib \
          g++-multilib \
          libgnutls28-dev \
          && sudo apt-get clean \
          && sudo rm -rf /var/lib/apt/lists/*

      - name: Compile ${{ matrix.platform }}
        id: compile_step
        shell: bash
        run: |
          cd ..
          rm -rf ./REG-LINUX
          git clone --branch master "https://github.com/REG-Linux/REG-Linux.git" ./REG-LINUX
          cd REG-LINUX
          git submodule init
          git submodule update
          
          pwd

          # Enable the flag to build QT6 from source
          sed -i s/#BR2_PACKAGE_REGLINUX_QT6=y/BR2_PACKAGE_REGLINUX_QT6=y/ configs/reglinux-board.common
          sed -i s/#BR2_PACKAGE_REGLINUX_QT6_BUILD_FROM_SOURCE=y/BR2_PACKAGE_REGLINUX_QT6_BUILD_FROM_SOURCE=y/ configs/reglinux-board.common
          sed -i s/#BR2_PACKAGE_QT6BASE_DEFAULT_QPA=\"wayland\"/BR2_PACKAGE_QT6BASE_DEFAULT_QPA=\"wayland\"/ configs/reglinux-board.common

          # Version
          qtversion=$(grep -m 1 REGLINUX_QT6_VERSION package/reglinux/libraries/reglinux-qt6/reglinux-qt6.mk | sed -e "s/.*=[ ]*//")
          echo "qtversion=${qtversion}" >> "$GITHUB_OUTPUT"
          

          pwd

          sudo ls -la /_w/REG-Qt6/REG-LINUX/configs/

          # Build
          sudo /_w/REG-Qt6/REG-LINUX/configs/createDefconfig.sh /_w/REG-Qt6/REG-LINUX/configs/reglinux-${{ matrix.platform }}
          sudo CCACHE_DISABLE=1 make O_=/_w/REG-Qt6/REG-LINUX/output/${{ matrix.platform }} BR2_EXTERNAL=/__w/REG-Qt6/REG-LINUX -C /__w/REG-Qt6/REG-LINUX/buildroot reglinux-${{ matrix.platform }}_defconfig
          cd output/${{ matrix.platform }}
          sudo CCACHE_DISABLE=1 make reglinux-qt6
          
          # Create built output directory
          sudo mkdir -p /__w/REG-Qt6/REG-QT6-COMPILED

          # Create package
          cd output/${{ matrix.platform }} || exit 1
          staging="$(cat build/staging.dir)"
          cat build/host-qt6*/.files-list-host.txt | cut -d ',' -f 2 | sed -e 's/\.\//host\//g' >qt6-host-files.txt
          cat build/qt6*/.files-list-staging.txt | cut -d ',' -f 2 | sed -e "s+\.\/+$staging\/+g" >qt6-staging-files.txt
          cat build/qt6*/.files-list.txt | cut -d ',' -f 2 | sed -e 's/\.\//target\//g' >qt6-target-files.txt
          cat qt6-host-files.txt qt6-staging-files.txt qt6-target-files.txt >filelist.txt
          find . | grep /host/ | grep Qt >>filelist.txt
          find . | grep /target/ | grep Qt >>filelist.txt
          awk -i inplace '!seen[$0]++' filelist.txt
          tar cvzf /__w/REG-Qt6/REG-QT6-COMPILED/reglinux-qt6-${qtversion}"-${{ matrix.platform }}.tar.gz -T filelist.txt
        
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.dorelease && ! cancelled() }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./REG-LINUX-COMPILED/
          merge-multiple: true
      - name: Create release
        uses: softprops/action-gh-release@master
        with:
          files: ./REG-LINUX-COMPILED/**/reglinux-qt6-*
          tag_name: ${{ needs.build.outputs.qtversion }}
          prerelease: false
          generate_release_notes: true
          name: ${{ needs.build.outputs.qtversion }}
